name: linting, tests, building
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  pipeline:
    runs-on: windows-latest
    strategy:
      matrix:
        node-version: [20.3.1]
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js environment
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: install modules
        run: npm install
      - name: build production project
        run: npm run build:prod
        if: always()
      - name: linting typescript
        run: npm run lint:ts
        if: always()
      - name: linting scss
        run: npm run lint:scss
        if: always()
      - name: unit tests
        run: npm run test:unit
      - name: build storybook
        run: npm run storybook:build
        if: always()
      - name: screenshot tests
        run: npm run test:ui:ci
